FROM php:8.2-fpm
WORKDIR /var/www/html
RUN apt-get update && apt-get install -y nginx
COPY ./etc/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf
COPY --chown=www-data:www-data --chmod=775 ./src/ /var/www/html/
EXPOSE 443
CMD ["/bin/sh", "-c", "php-fpm -D && nginx -g 'daemon off;'"]