version: "3.8"

services:
  php:
    image: php:8.2-fpm
    volumes:
      - ./src:/var/www/html:rw
    restart: unless-stopped

  nginx:
    depends_on:
      - php
    image: nginx:latest
    ports:
      - "443:443"
    volumes:
      - ./src:/var/www/html:ro
      - ./etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./etc/ssl/certs/rr-origin.pem:/etc/ssl/certs/rr-origin.pem:ro
      - ./etc/ssl/private/rr-private-key:/etc/ssl/private/rr-private-key.pem:ro
    restart: unless-stopped

