FROM php:8.2-fpm
WORKDIR /var/www/html
RUN apt-get update && apt-get install -y nginx supervisor
COPY ./etc/nginx/conf.d/default-supervisor.conf /etc/nginx/conf.d/default.conf
COPY ./etc/supervisor/conf.d/supervisord.conf /etc/supervisor/conf.d/supervisord.conf
COPY --chown=www-data:www-data --chmod=775 ./src/ /var/www/html/
EXPOSE 443
CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]