FROM php:8.2-apache
WORKDIR /var/www/html
COPY ./etc/apache2/sites-available/000-default.conf /etc/apache2/sites-available/000-default.conf
RUN a2enmod rewrite ssl && a2ensite 000-default.conf
EXPOSE 443
COPY --chown=www-data:www-data --chmod=775 ./src/ /var/www/html/
CMD ["apache2-foreground"]
