version: '3.8'

services:
  hatshop:
    restart: unless-stopped
    image: ghcr.io/wilsonify/c01-an-introduction-to-php:latest
    ports:
      - "443:443"
    volumes:
      - ./etc/ssl/certs/rr-origin.pem:/etc/ssl/certs/rr-origin.pem
      - ./etc/ssl/private/rr-private-key.pem:/etc/ssl/private/rr-private-key.pem
